sudo: required

matrix:
  include:
    - language: javascript
      addons:
          chrome: "stable"
          firefox: "latest"
      before_install:
        - mkdir qunit
        - wget -O qunit/qunit-1.18.0.css http://code.jquery.com/qunit/qunit-1.18.0.css
        - wget -O qunit/qunit-1.18.0.js  http://code.jquery.com/qunit/qunit-1.18.0.js
        - nvm install 8
        - npm install testem
        - ./node_modules/.bin/testem launchers
        # A newer version of libnss3 is needed for the latest Chrome version
        - sudo apt-get --only-upgrade install libnss3

      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      script:
        - ./node_modules/.bin/testem --launch "Firefox,Headless Chrome" -t www/tests/qunit/run_tests.html ci

    - language: python
      python: 3.7
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      before_install: pip install --upgrade pip
      before_script: pip install flake8
      script:
        - EXCLUDE=./.*,www/src/Lib/test/badsyntax_3131.py
        # stop the build if there are Python syntax errors
        - flake8 . --exclude=$EXCLUDE --exit-zero --select=E999 --show-source --statistics
